description: |
  Install GovCMS distribution.

parameters:
  php_version:
    type: string
    default: "8.3-apache"
    description: "The version of PHP to use."

executor:
  name: default
  php_version: << parameters.php_version >>

steps:
  - checkout
  - run:
      name: Install GovCMS distribution
      command: >
        composer update --profile --prefer-dist --optimize-autoloader --no-scripts
  - run:
      name: List all packages within the GovCMS distribution
      command: |
        composer show -i -D
  - run:
      name: List outdated packages within the GovCMS distribution
      command: |
        composer outdated -D
