description: |
  Validate composer.json.

parameters:
  php_version:
    type: string
    default: "8.3-apache"
    description: "The version of PHP to use."

executor:
  name: default
  php_version: << parameters.php_version >>

steps:
  - checkout
  - run:
      name: Validate distribution composer.json
      command: |
        composer validate --no-check-all
        <<include(scripts/check-patches.sh)>>
