description: |
  Validate composer.json.

executor:
  name: default

working_directory: /app

steps:
  - run:
      name: Clean Working Directory
      command: find /app -mindepth 1 -delete
  - checkout
  - run:
      name: Install GovCMS Dependencies
      command: composer update --profile --prefer-dist --optimize-autoloader
  - run:
      name: Validate distribution composer.json
      command: |
        composer validate --no-check-all
  - run:
      name: Check applied patches
      command: <<include(scripts/check-patches.sh)>>
