description: >
  GovCMS Tests Docker Image.
docker:
  - image: 'govcmstesting/php:<<parameters.php_version>>'
  - image: 'cimg/mariadb:<<parameters.mariadb_version>>'
parameters:
  php_version:
    default: "8.2-apache"
    description: >
      The version of PHP to run your tests with.
    type: string
  mariadb_version:
    default: "10.11"
    description: >
      The version of mariadb to run your tests with.
    type: string
