description: >
  GovCMS Tests Docker Image.
docker:
  - image: 'govcmstesting/php::<<parameters.php-version>>'
  - image: 'cimg/mariadb::<<parameters.mariadb-version>>'
parameters:
  php-version:
    default: "8.2-apache"
    description: >
      The version of PHP to run your tests with.
    type: string
  mariadb-version:
    default: "10.11"
    description: >
      The version of mariadb to run your tests with.
    type: string